title: Deyao's Blog
author: Deyao Chen
email: chendeyao000@gmail.com
description: 
  Thoughts on math, programming and stuff
long_description: > # this means to ignore newlines until "twitter_username:"
  I am just another person trying to do something useful for the world. I write mostly about math and programming, occasionally about some other randoms thoughts I have.

# social links
instagram_username: deyaochen

github_username:  de0ch
source_code: https://github.com/de0ch/de0ch.github.io
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# twitter_username: deyaochen
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
